name: Build Enjoy App
on: 
  workflow_dispatch:
    inputs:
      os:
        type: choice
        description: Choose platform
        options:
          - macos-latest
          - windows-latest
          - ubuntu-latest
      arch:
        type: choice
        description: Choose Arch
        options:
          - x64
          - arm64

jobs:
  build:
    runs-on: ${{ github.event.inputs.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install dependencies
        run: yarn install
      - name: Install certificate
        if: github.event.inputs.os == 'macos-latest'
        run: ./enjoy/scripts/add-macos-cert.sh
      - name: Make
        env:
          GITHUB_TOKEN: ${{ secrets.PUBLISH_TOKEN }}
          PACKAGE_OS_ARCH: ${{ github.event.inputs.arch }}
          APPLE_ID: ${{ secrets.APPLE_ID }}
          APPLE_APP_PASSWORD: ${{ secrets.APPLE_APP_PASSWORD }}
          APPLE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}
          MACOS_CERTIFICATE_APPLICATION_BASE64: ${{ secrets.MACOS_CERTIFICATE_APPLICATION_BASE64 }}
          MACOS_CERTIFICATE_PASSWORD: ${{ secrets.MACOS_CERTIFICATE_PASSWORD }}
        run: yarn run make:enjoy --arch=${{ github.event.inputs.arch }}
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Enjoy-${{ github.event.inputs.os }}-${{ github.event.inputs.arch }}-build
          path: enjoy/out/make/**/*
