name: Build Enjoy App
on: workflow_dispatch

jobs:
  publish:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install dependencies
        run: yarn install
      - name: Build
        env:
          GITHUB_TOKEN: ${{ secrets.PUBLISH_TOKEN }}
          APPLE_ID: ${{ secrets.APPLE_ID }}
          APPLE_APP_PASSWORD: ${{ secrets.APPLE_APP_PASSWORD }}
          APPLE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}
          MACOS_CERTIFICATE_APPLICATION_BASE64: ${{ secrets.MACOS_CERTIFICATE_APPLICATION_BASE64 }}
          MACOS_CERTIFICATE_PASSWORD: ${{ secrets.MACOS_CERTIFICATE_PASSWORD }}
        run: yarn make:enjoy
      - if: matrix.os == 'macos-latest'
        name: Build macOS arm64
        env:
          GITHUB_TOKEN: ${{ secrets.PUBLISH_TOKEN }}
          APPLE_ID: ${{ secrets.APPLE_ID }}
          APPLE_APP_PASSWORD: ${{ secrets.APPLE_APP_PASSWORD }}
          APPLE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}
          MACOS_CERTIFICATE_APPLICATION_BASE64: ${{ secrets.MACOS_CERTIFICATE_APPLICATION_BASE64 }}
          MACOS_CERTIFICATE_PASSWORD: ${{ secrets.MACOS_CERTIFICATE_PASSWORD }}
          PACKAGE_OS_ARCH: arm64
        run: | 
          ./enjoy/scripts/add-macos-cert.sh
          yarn run make:enjoy --arch=arm64
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Enjoy-${{ matrix.os }}
          path: ./enjoy/output/make/**/*
