name: Deploy Enjoy Docs website

on:
  push:
    branches:
      - main
    paths:
      - "enjoy-docs/**"
  pull_request:
    branches:
      - main
    paths:
      - "enjoy-docs/**"

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      # checkout the code
      - uses: actions/checkout@v4

      - uses: actions/cache@v4
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}

      - name: Setup node env
        uses: actions/setup-node@master
        with:
          node-version: "20"

      - name: Install Independents
        run: yarn install

      - name: Build
        run: yarn docs:build

      - name: Deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy .vitepress/dist --project-name=enjoy-docs
          workingDirectory: "enjoy-docs"

