name: Release Enjoy App
on: workflow_dispatch

jobs:
  publish:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: install dependencies
        run: yarn install
      - name: publish
        env:
          GITHUB_TOKEN: ${{ secrets.PUBLISH_TOKEN }}
        run: yarn publish:enjoy
      - if: matrix.os == 'macos-latest'
        env:
          GITHUB_TOKEN: ${{ secrets.PUBLISH_TOKEN }}
          PACKAGE_OS_ARCH: arm64
        run: yarn run publish:enjoy --arch=arm64
