name: Test Enjoy App
on: workflow_dispatch
jobs:
  test:
    timeout-minutes: 60
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          [
            macos-11,
            macos-12,
            macos-13,
            macos-latest,
            windows-latest,
            ubuntu-latest,
          ]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 20
      - name: Install dependencies
        run: npm install -g yarn && yarn
      - name: Install Playwright Browsers
        run: yarn playwright install --with-deps
      - name: Package
        run: yarn package:enjoy
      - name: Run Playwright tests
        run: yarn test:enjoy
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
