name: Test Enjoy App
on: workflow_dispatch
jobs:
  test:
    timeout-minutes: 60
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          [
            macos-11,
            macos-12,
            macos-13,
            macos-latest,
            windows-latest,
            ubuntu-latest,
          ]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 20
      - name: Install dependencies
        run: npm install -g yarn && yarn
      - name: Install Playwright Browsers
        run: yarn workspace enjoy playwright install --with-deps
      - if: matrix.os == 'ubuntu-latest'
        name: Run tests with xvfb-run
        run: |
          xvfb-run --auto-servernum --server-args="-screen 0 1280x960x24" -- yarn test:enjoy
      - if: matrix.os != 'ubuntu-latest'
        name: Run tests
        run: yarn test:enjoy
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
